apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: clickhouse-


resources:
- configmap.yaml
- init-scripts-secret.yaml
- scripts-configmap.yaml
- secret.yaml
- service-headless.yaml
- service.yaml 
- statefullset.yaml

