apiVersion: v1
kind: Secret
metadata:
    name: sec
type: Opaque
data:
    admin-password: ENC[AES256_GCM,data:eEQaBNpIir6D6SCD,iv:l+xN49k6ppDLH/yRh00cpGVGM1ECHD5wFtonzspcJ+c=,tag:BYOPYf5mYY1sD8Lbq84RzA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fgjldv96xlre9ev5v5v0l3tg4p9hv9gtfyhd403dm43n296cxf7su3nw33
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvNlhjVTQ1dUVZTFBPckQw
            SmRPZWRzOFdxcWhVZUc5cFowZFBxaFdjbmxJCnlndWNSOWJ5eHZrb3p2aHFraksy
            OWhNZ09wVDE4d1ZRTWJ6OEpWWEYxSEEKLS0tIElxc2ZXdUZXZUt6MnBEOW9NdU9B
            Tnh1aXkzQ3YxZlBsRFNyNFo2cTkrNGsKrhYaxhCDLTOdvk+lrV5lprAWaYWm9QCk
            pVr+Ieegpccpe3MJk+AJNRmyZ9J7uXdcqwscWnOTb04Oa5j9pMXf3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-11T18:59:06Z"
    mac: ENC[AES256_GCM,data:MF3eu3ltrKq4p1PLyBuT0VVe3S3sTmlGcWewgmrR0cTlkzupiSOBqRxpXiBlMmrXDRs2/U7cVFrc03FgMoqQ9P06vBGv8KYGjir5giRfIIfPOYFDH7SKQUiUrDe/Vm/UX868Ly3qibTjEcBPgG6mhOQc2bz/zCdgiKhnK3LvcuA=,iv:IawcG5jrMMCkDxrv2HEdS2yNjELBybQucc4aEaC6Pwc=,tag:Ayl39eq9am5+0HtlqXsMow==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
