apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tn-openbsw-basis
namePrefix: plausible-

buildMetadata: [originAnnotations]

resources:
- manifests/postgres/
- manifests/clickhouse/
- manifests/plausible/
- manifests/mailcatcher/

