apiVersion: v1
kind: Secret
metadata:
    name: sec
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:l/FKJUaD61crI7uliFwzHTW4PaE=,iv:87yJzKXqLj5WCT2uAypHdy2M8EXoEQLqoNEG3RYXzcE=,tag:2oeQRWiTblSe0pYkkRHifg==,type:str]
    username: ENC[AES256_GCM,data:c0PtuPB+FINg,iv:F7ISMorYN1G+mPfJDkvu7Rj+SpFhXun/fDcjCYB3C0I=,tag:+JaSkq1Za7VdD2iUFbk5Bw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fgjldv96xlre9ev5v5v0l3tg4p9hv9gtfyhd403dm43n296cxf7su3nw33
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyRDBhcnBiRUV4NlNXSi9F
            QlhuVlZhYmFwSFQxZGdJU2FmbXpuS2NpVUc0CmVGTzNuSUhSZEtBaDg5d1VaSnZC
            ZDRlWGRwaGoyQTFuNkhMclkwcmFMTE0KLS0tIDFPT1J0SitweTl1bi9xTFBqWFBJ
            SHhRWVJRYXh4Zkt2VVYxaGE0MTQ4RWMKWdxtJYsvb58nJh2rfolBo5BRsld0WJm7
            EigSnD3CDdvguKj1Mg6YZZfcks6cdJu08wfTxGTQoIFTnOXwnfCZQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-11T18:59:21Z"
    mac: ENC[AES256_GCM,data:nSqM3OVpJCVHhbmyVjSjwxgnEzOC7neZHREDHgiJDijgkCcKtYrMdoTSp3JKpERHYvovVWkEuguEizva3T5fxZfs7SNExAV9ajwJgFY0+GJAQItP3M5bElpRkzPKZIx4pv219YP/5CzwJwiCXr7ynypHDVAeXtc0UuSUjei+ZFc=,iv:gpemYKoDQ3d3TWmn4FV1ozEz94gObd2zVBHeog5UDew=,tag:9Ku8hl1lWukQ+2l+nYkUsA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
