apiVersion: v1
kind: Secret
metadata:
    name: sec-super
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:nxsWcIqpHrmGrrZcRyJvsiUc,iv:9TGomjQ5/kt7yV+HOODudnEi13mVlPZ7CTWNljuEF1w=,tag:hsOB83ueBt8WQdIgNHnYxA==,type:str]
    username: ENC[AES256_GCM,data:pW0kFqlHC50=,iv:i+Lvb4NAag18UjSIhSU2LJ7IDr18Mir4hlQYyAGV4Go=,tag:/lLODMGTtSECk4/xqWf4kQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fgjldv96xlre9ev5v5v0l3tg4p9hv9gtfyhd403dm43n296cxf7su3nw33
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoQngrZURoa0E1RG9XeE9J
            dGdEbG1IczdmRUZGOFBNcnZERTMxR2dhUVU4CnVGeHhuUnQ1bHdXOFVjTVZNSkFo
            OWduNndSM0FaSS8yMmM1MVhQcDJXL28KLS0tIEVGQmNlN1NFYkNsZkRjR0g3NkdM
            SXlDYlp0QkhPK2FRRzZzM2JTNDdhd2sKLr9ewTY3RejG7b6M2+fOxtK77DzwyJ5X
            rvIpSIr6edrORhNHdYfGjZIz7ImtVN5LAywGWDWrNxcT912BX86C7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-11T18:59:25Z"
    mac: ENC[AES256_GCM,data:vQbbsajhdCS5oA8uGIyp2NfKJ0732APJp9uEcCRebB6kKTNXFAvf4QlK7ZRxfpeVW6vNDijZihzI998Z4WuBoDrUkOLckMgEzVg6fLYQKMigoYaz5n+I5g+xCe1yAA8MQJ2CVa+hdJjayk1qngAspKwj19+Btgq0AOzbaEvjSa4=,iv:ws0htdICQJ+qwDC5L6EzumM1Tpu7spLgTVX9LJu1i1w=,tag:vFOtjt+aUF1tYdDznHoMKA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
