apiVersion: v1
kind: Secret
metadata:
    name: plausible-plausible-analytics
type: Opaque
stringData:
    SECRET_KEY_BASE: ENC[AES256_GCM,data:N8C7tSZYLySEpk782kG27eEZQB/oQ5QWxh2UQ2D8MWcJEUgj05Lkt8lU4F4OF6czCuCgavFC5pa/ccKWApluRQ==,iv:OmH0FqLVL+Vio61o1//zenGVQ10IEVRF8wamh6CH7EQ=,tag:FEwI1iSWIjSj1w0xI1h/xg==,type:str]
    TOTP_VAULT_KEY: ENC[AES256_GCM,data:ndS3RnBGHApLd72M/dUWqk/aR16cExdaCpqgIN6OhH5o96fOYx0HIBZqaaI=,iv:ZWmprFJt92tijSbyRmhSvAy06y6wN9jPDIk6TR14Uys=,tag:EeVGVL3R4vOPXwNSAfhmnw==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:ttGtRbnI7dUZIYxLPIIQg6Az+Z1UWiSgYXp6azrFm/e4Zui8tcH6WP1277YJIWHrmK3qiekX1AdoQO0T4xev6JLvtmbOhClcetEoi61oOxVK,iv:cem21gRPdJvXs9jU1NxrACs84I9fb86lUXZXiz9ERSc=,tag:dx/YYreLQCD5WItXChT+Kw==,type:str]
    CLICKHOUSE_DATABASE_URL: ENC[AES256_GCM,data:l820AKqO84mkd+3r6LDz/tMtE/j61TYZj78ZCimpoJl0bYtUOaeF/FUza6up7Q+vOThpOrvXRhKMcjfl+7NmO1MJxkbopcaEm9PFZOqOt7KNpmkiTSSS,iv:awTm1s0z3BJ/UcctQjR3lhJpzdYhKA0U2Tq6CdhVypQ=,tag:hRvFy7YcT3fXTRX4Ogo44g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fgjldv96xlre9ev5v5v0l3tg4p9hv9gtfyhd403dm43n296cxf7su3nw33
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVclR2Y2NzQWQ1RUtlMmph
            YktWVjExZ2owQUdkVGdTMjNDOWVRZ1BaNXlVCkw0Vm5TZVdUR2lzQ0xRbDZNQ0Z5
            anFUUnJWK1pZZlhKU213TkM0S3VtdkEKLS0tIGFYdGduNGFmQk9veHNnbnkyeG8x
            T04wTEZLSG5ZbExpT2JFTW5jVVpTWmsKG0wJHFXrFi6MtaD8B6b4pInIYQWtgked
            /28HhWNEcC54ReU8ZTpuMZ7VHI4feR13LgJDSeehr3BnbUeroU+d6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-11T18:59:13Z"
    mac: ENC[AES256_GCM,data:ELXX56RcUOf4mg4eWfMSQojbHm6C4it0sH/kJpVf59QSAxB1vtuunGtzz8Le7ZAq3GDHrVNEmjTOtTWmXk2tghof/Tojc1O39McKORhYGRfUTq/zgCoFw0QgflLK2ZgAlLqBYZC3mn2OlKa1Ugy+fZlrcb0J6ie2WwjMNMLrpP0=,iv:ilT72xrooaRgN5G3EEbViJ3UehDEjKq1UwzE6mqDGfo=,tag:DPtcQhRpGevfDHc8qtyHMQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
